import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/hooks/useAuth";
import { ThemeProvider } from "@/hooks/useTheme";
import ClientLayout from "./ClientLayout";
import { STORAGE_KEYS } from "@/constants";
import { ErrorBoundary } from "@/components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('${STORAGE_KEYS.THEME}');
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else if (!theme) {
                    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                    if (prefersDark) {
                      document.documentElement.classList.add('dark');
                    }
                  }
                } catch (e) {}
                
                // Filtrar erros BackendOffline do console
                const originalError = console.error;
                console.error = function(...args) {
                  // Verificar se algum argumento é um erro BackendOffline
                  const shouldSuppress = args.some(arg => {
                    if (arg && typeof arg === 'object') {
                      // Verificar propriedade name
                      if (arg.name === 'BackendOffline') return true;
                      // Verificar mensagem
                      const message = String(arg.message || '').toLowerCase();
                      if (message.includes('servidor está temporariamente indisponível') ||
                          message.includes('backend está em execução') ||
                          message.includes('backend offline')) {
                        return true;
                      }
                    }
                    // Verificar se é string
                    const str = String(arg || '').toLowerCase();
                    if (str.includes('backend offline') ||
                        str.includes('servidor está temporariamente indisponível')) {
                      return true;
                    }
                    return false;
                  });
                  
                  // Só logar se não for BackendOffline
                  if (!shouldSuppress) {
                    originalError.apply(console, args);
                  }
                };
              })();
            `,
          }}
        />
        <ErrorBoundary>
          <ThemeProvider>
            <AuthProvider>
              <ClientLayout>{children}</ClientLayout>
            </AuthProvider>
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
