up: 
	@echo "Starting Docker Compose..."
	@docker-compose up -d

down:
	@echo "Stopping Docker Compose..."
	@docker-compose down

build:
	@echo "Building Docker Compose..."
	@docker-compose build

fast-run:
	@echo "Building and running Project..."
	@./mvnw spring-boot:run