spring.application.name=clusterforge
spring.docker.compose.enabled=false
clusterforge.docker.host=unix:///var/run/docker.sock
docker.templates.path=./data/templates
docker.volumes.basePath=./data/volumes
# Range de portas para alocação dinâmica (portas do host)
clusterforge.ports.range.start=9000
clusterforge.ports.range.end=9999
spring.datasource.url=jdbc:h2:file:./data/db/clusterforge;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true